import type { GrowthLever } from '@/types'

export const DEFAULT_LEVERS: GrowthLever[] = [
  {
    id: 'seo',
    name: 'SEO & Content',
    description: 'Organic search optimisation and technical blog content targeting high-intent keywords.',
    category: 'acquisition',
    icon: '🔍',
    impact: 6,
    effort: 4,
    timeToEffect: 3,
    cost: 3,
    enabled: false,
  },
  {
    id: 'referral',
    name: 'Referral Program',
    description: 'Incentivised peer-to-peer referrals with rewards for both referrer and referee.',
    category: 'referral',
    icon: '🔗',
    impact: 8,
    effort: 5,
    timeToEffect: 1,
    cost: 5,
    enabled: false,
  },
  {
    id: 'pricing',
    name: 'Pricing Restructure',
    description: 'Tiered pricing with a freemium entry point to widen top-of-funnel and upsell premium.',
    category: 'revenue',
    icon: '💰',
    impact: 7,
    effort: 6,
    timeToEffect: 2,
    cost: 2,
    enabled: false,
  },
  {
    id: 'partnerships',
    name: 'Strategic Partnerships',
    description: 'Co-marketing with colleges, bootcamps, and hiring platforms for distribution leverage.',
    category: 'acquisition',
    icon: '🤝',
    impact: 9,
    effort: 7,
    timeToEffect: 2,
    cost: 4,
    enabled: false,
  },
  {
    id: 'onboarding',
    name: 'Onboarding Optimisation',
    description: 'Reduce activation time-to-value from 7 days to <48 hours with guided first session.',
    category: 'activation',
    icon: '🚀',
    impact: 7,
    effort: 5,
    timeToEffect: 1,
    cost: 3,
    enabled: false,
  },
  {
    id: 'community',
    name: 'Community & Discord',
    description: 'Active peer community, alumni network, and weekly live sessions for retention.',
    category: 'retention',
    icon: '👥',
    impact: 6,
    effort: 4,
    timeToEffect: 2,
    cost: 2,
    enabled: false,
  },
  {
    id: 'paid_ads',
    name: 'Performance Marketing',
    description: 'Targeted paid acquisition on LinkedIn, YouTube, and Google for high-LTV segments.',
    category: 'acquisition',
    icon: '📣',
    impact: 5,
    effort: 3,
    timeToEffect: 1,
    cost: 8,
    enabled: false,
  },
  {
    id: 'product_led',
    name: 'Product-Led Growth',
    description: 'Embed virality in the product: shareable certificates, public profiles, leaderboards.',
    category: 'product',
    icon: '⚡',
    impact: 8,
    effort: 8,
    timeToEffect: 3,
    cost: 5,
    enabled: false,
  },
  {
    id: 'enterprise',
    name: 'B2B / Enterprise Sales',
    description: 'Bulk enrolment deals with companies for upskilling cohorts of 50–500 employees.',
    category: 'revenue',
    icon: '🏢',
    impact: 9,
    effort: 8,
    timeToEffect: 3,
    cost: 6,
    enabled: false,
  },
  {
    id: 'retention_email',
    name: 'Personalised Re-engagement',
    description: 'ML-driven email + push sequences targeting at-risk users before churn.',
    category: 'retention',
    icon: '📧',
    impact: 5,
    effort: 3,
    timeToEffect: 1,
    cost: 2,
    enabled: false,
  },
]

export const CATEGORY_COLORS: Record<string, string> = {
  acquisition: '#FF5C29',
  activation:  '#F59E0B',
  retention:   '#22C55E',
  referral:    '#8B5CF6',
  revenue:     '#06B6D4',
  product:     '#EC4899',
}

export const CATEGORY_LABELS: Record<string, string> = {
  acquisition: 'Acquisition',
  activation:  'Activation',
  retention:   'Retention',
  referral:    'Referral',
  revenue:     'Revenue',
  product:     'Product',
}
